title: Jackie Do
description: My Personal Blog
author: Jackie Do
logo: /hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/jackiedo91
about: Ruby on Rails developer

baseurl: "https://jackiedo91.github.io/jackie_do_blog"
url: "https://jackiedo91.github.io/jackie_do_blog"

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
